name=ESP32-IoT-Framework
includes=WiFiManager.h,webServer.h,updater.h,configManager.h,timeSync.h,dashboard.h,DiagManager.h,OTAManager.h
version=0.0.5
author=JoergTiedemann
maintainer=JoergTiedemann
sentence=IoT Framework based on the famous ESP8266 IoT Framwork from MaakBas
paragraph=ESP32 Framework for IoT projects implementing HTTPS requests, a React web interface, WiFi manager, configuration manager, file manager and OTA updates
category=Other
url=https://github.com/JoergTiedemann/ESP32-IoT-Framework
architectures=esp32
license=GPL-3.0
