; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
monitor_filters = esp32_exception_decoder

extra_scripts = pre:preFirmwareVersion.py
				add_lib_info.py
debug_tool = esp-prog
debug_init_break = tbreak setup
build_flags = 
	; Debug-Level als Symbolname
	;-DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG
	; kein Logging im Core um FlashSize zu sparen vorher was das 1
	-DCORE_DEBUG_LEVEL=0
	; kein WIFI-Logging  um FlashSize zu sparen
	-DLOG_LOCAL_LEVEL=0

	; oder numerisch (4 = DEBUG)
	; -DCORE_DEBUG_LEVEL=4
	; Farben aktivieren
	;-DCONFIG_ARDUHAL_LOG_COLORS=1
	-DREBUILD_HTML
	-DDASHBOARD_PATH=dashboard.json -DREBUILD_DASHBOARD
	-DCONFIG_PATH=configuration.json -DREBUILD_CONFIG
    -D DISABLE_FIRESTORE
    -D DISABLE_FIRESTORE_QUERY
	-D DISABLE_RULESETS
	-D DISABLE_STORAGE
	-D DISABLE_FUNCTIONS
    -D DISABLE_OTA
    -D DISABLE_FS
	-D FIREBASE_DISABLE_NATIVE_ETHERNET

	-D ENABLE_DATABASE
	-D ENABLE_MESSAGING
	-D ENABLE_SERVICE_AUTH

	;###############################################################
  	; TFT_eSPI library setting here (no need to edit library files):
	; ILI9341 nur zur Diagnose für das grosse rote TouchDisplay der Rest (was verbaut ist) ist ST7735
  	;###############################################################
  -D USER_SETUP_LOADED=1                        ; Set this settings as valid
;  -D ILI9341_2_DRIVER=1                           ; Select ILI9163_2 driver see https://github.com/Bodmer/TFT_eSPI/issues/1172 
 ; -D ILI9341_DRIVER=1                           ; Select ILI9163 driver
  -D ST7735_DRIVER=1      						; Select ST7735 Driver
  -D ST7735_BLACKTAB=1 
  -D TFT_MOSI=23
  -D TFT_SCLK=18
  -D TFT_CS=5
  -D TFT_DC=2                                   ; Data/Comand pin
  -D TFT_RST=-1                                 ; Reset pin
  -D LOAD_GLCD=1                                ; Load Fonts
 ; -D SPI_FREQUENCY=40000000                     ; Set SPI frequency fuer ILI9341
  -D SPI_FREQUENCY=10000000 					; fuer ST7735


upload_speed = 921600
board_build.f_flash = 80000000L
board_build.partitions = min_spiffs.csv
lib_deps = 
	ESP32Async/ESPAsyncWebServer@3.11.2
